name: Tests

on:
  pull_request:
    paths-ignore: [ 'dist/**', '*.md' ]
  push:
    paths-ignore: [ 'dist/**', '*.md' ]

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Run PHP tests
        run: vendor/bin/pest
